[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm = "0.10.3"
bincode = { version = "2.0.1", features = ["serde"] }
rand = "0.9.1"
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.16"
